"""Schemas for chat and conversational AI interactions."""
import uuid
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, ConfigDict


class ChatMessage(BaseModel):
    """Single chat message in a conversation thread."""
    role: str  # "user", "assistant", "system"
    content: str


class ChatRequest(BaseModel):
    """User request payload for conversational AI."""
    messages: List[ChatMessage]
    business_id: Optional[uuid.UUID] = None
    connected_account_id: Optional[uuid.UUID] = None
    auto_publish: bool = False  # If True, automatically publish to LinkedIn once brief is finalized


class LinkedInPostBrief(BaseModel):
    """Finalized LinkedIn post brief generated by Miso AI."""
    topic: str
    content_text: str
    suggested_hashtags: List[str] = []
    call_to_action: Optional[str] = None
    recommended_time: Optional[str] = None


class ChatResponse(BaseModel):
    """AI Response payload."""
    reply: str
    is_finalized: bool = False
    brief: Optional[LinkedInPostBrief] = None
    published_post_id: Optional[uuid.UUID] = None
